[workspace]
changelog_update = true
dependencies_update = true
features_always_increment_minor = true
git_release_enable = false
git_tag_enable = true
pr_labels = ["release"]
publish = false

[[package]]
name = "forma-core"
publish = true

[[package]]
name = "forma-proc-macro"
publish = true

[[package]]
name = "forma-schema"
publish = true
