f7r-core:
  commonDeployment:
    name: monitor-server
    namespace: f7r-monitor-server
    replicas: 20
    labels:
      adaptor: monitor-server
    availability:
      minReadySeconds: 10
      maxSurge: 25%
      maxUnavailable: 25%
    resource:
      minCpu: 100m
      minMemory: 256Mi
      maxCpu: 250m
      maxMemory: 512Mi
  commonService:
    name: monitor-server
    namespace: f7r-monitor-server
    labels:
      adaptor: monitor-server
  port:
    serverPort: 3000
    exposePort: 3000
    protocol: TCP