[package]
name = "forma-core"
version = "0.1.0"
edition = "2024"
description = "Formatier API core"
license = "MIT"

[dependencies]
woothee = "0.13.0"

axum = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true }
thiserror = { workspace = true }
forma-proc-macro = { workspace = true, version="0.1.1" }
chrono = { workspace = true }
mongodb = { workspace = true }
redis = { workspace = true }
rustls = { workspace = true }
reqwest = { workspace = true }

[dev-dependencies]
rand = "0.10.2"
