f7r-core:
  commonDeployment:
    name: interspace-service
    namespace: f7r-interspace-service
    replicas: 8
    labels:
      service: interspace-service
    availability:
      minReadySeconds: 10
      maxSurge: 20%
      maxUnavailable: 20%
    resource:
      minCpu: 100m
      minMemory: 256Mi
      maxCpu: 250m
      maxMemory: 512Mi
  commonService:
    name: interspace-service
    namespace: f7r-interspace-service
    labels:
      adaptor: interspace-service
  port:
    serverPort: 3000
    exposePort: 3000
    protocol: TCP